watermark_text = [
    "Sample", "Demo", "Confidential", "Draft", "Private", "For Review",
    "Do Not Copy", "Internal Use", "Restricted", "Top Secret",
    "CompanyName", "MyBrand", "Watermark", "ImageTest", "Preview",
    "TrainingOnly", "ConfidentialUse", "Protected", "Proprietary",
    "BetaVersion", "Temp", "ClientCopy", "NotForSale", "Security",
    "MyLogo", "DraftOnly", "Placeholder", "Confidential2025",
    "Testing123", "ConfidentialCopy", "InternalOnly", "ForEvaluation",
    "ConfidentialData", "RestrictedCopy", "CompanyWatermark", "SampleText",
    "ConfidentialInfo", "DemoUse", "ConfidentialImage", "ConfidentialBrand",
    "ConfidentialNote", "ConfidentialFile", "ConfidentialAccess",
    "ConfidentialMark", "ConfidentialTest", "ConfidentialAsset",
    "ConfidentialDraft", "ConfidentialCode", "ConfidentialSample",
    "ConfidentialVersion", "ConfidentialWatermark", "ConfidentialEdition",
    "ConfidentialContent", "ConfidentialDocument", "ConfidentialRelease",
    "ConfidentialTraining", "ConfidentialStorage", "ConfidentialArchive",
    "ConfidentialLicense", "ConfidentialPreview", "ConfidentialControl",
    "ConfidentialProject", "ConfidentialClient", "ConfidentialDesign",
    "ConfidentialDrafts", "ConfidentialReview", "ConfidentialWork",
    "ConfidentialPrivate", "ConfidentialInternal", "ConfidentialRestricted",
    "ConfidentialTop", "ConfidentialSecure", "ConfidentialBlock",
    "ConfidentialSystem", "ConfidentialCompany", "ConfidentialImageSet",
    "ConfidentialDemo", "ConfidentialResearch", "ConfidentialKey",
    "ConfidentialLabel", "ConfidentialMarking", "ConfidentialNotice",
    "ConfidentialSheet", "ConfidentialTransfer", "ConfidentialLayer",
    "ConfidentialDataSet", "ConfidentialRecord", "ConfidentialDocs",
    "ConfidentialImage2025", "ConfidentialDraft2025", "ConfidentialVersion2",
    "ConfidentialCheck", "ConfidentialPattern", "ConfidentialTesting",
    "ConfidentialPicture", "ConfidentialAsset2025", "ConfidentialSeal",
    "ConfidentialTrial", "ConfidentialAlpha", "ConfidentialBeta",
    "ConfidentialGamma", "ConfidentialOmega", "ConfidentialDelta",
    "ConfidentialSigma", "ConfidentialZeta", "ConfidentialKappa",
    "ConfidentialTheta", "AlphaTech", "BetaWorks", "GammaCorp", "DeltaSoft", "EpsilonLabs",
    "ZetaSystems", "OmegaGlobal", "NovaVision", "LunarTech", "SolarEdge",
    "VertexDynamics", "QuantumSolutions", "NeonWorks", "ApexSystems", "CyberNova",
    "BlueSkyTech", "IronCladSolutions", "StellarNet", "FusionSoft", "NextGenLabs",
    "PulseCore", "CrystalTech", "RedStoneCorp", "WaveForm", "ZenithWorks",
    "HyperionSystems", "AuroraTech", "TitanEdge", "SkyBridge", "EverestGlobal",
    "StormWorks", "NebulaDynamics", "CyberLink", "PixelSoft", "CloudNova",
    "VertexLabs", "RadiantTech", "SilverLine", "PrismWorks", "AxionSystems",
    "PrimeCore", "FalconTech", "IronWorks", "PioneerLabs", "EchoVision",
    "SummitSoft", "DataSphere", "BrightWave", "QuantumEdge", "CoreLogic",
    "EpicTech", "StratoWorks", "TrueNorthLabs", "InfinityGlobal", "NextPhase",
    "VectorWorks", "RapidEdge", "IgniteTech", "CrystalCore", "StormNet",
    "CyberSphere", "MegaTech", "VertexCorp", "BlueOcean", "SkyLabs",
    "PulseWave", "AstroDynamics", "SolarisGlobal", "WhitePeak", "CloudBridge",
    "IronCore", "OptimaTech", "RedWave", "AuroraEdge", "VortexLabs",
    "MetaCore", "DataForge", "StarLink", "NeoSystems", "EagleVision",
    "BrightPath", "ZenCore", "LunaSoft", "NovaEdge", "IronShield",
    "SummitGlobal", "VertexDynamics", "PulseWorks", "CyberEdge", "CrystalLabs",
    "PrimeWave", "BlueStone", "CoreVision", "EchoTech", "NextWave",
    "CloudSphere", "RapidSystems", "SilverPeak", "SolarNet", "QuantumCore", "Alpha Tech", "Beta Works", "Gamma Corp", "Delta Soft", "Epsilon Labs",
    "Zeta Systems", "Omega Global", "Nova Vision", "Lunar Tech", "Solar Edge",
    "Vertex Dynamics", "Quantum Solutions", "Neon Works", "Apex Systems", "Cyber Nova",
    "Blue Sky Tech", "Iron Clad Solutions", "Stellar Net", "Fusion Soft", "NextGen Labs",
    "Pulse Core", "Crystal Tech", "Red Stone Corp", "Wave Form", "Zenith Works",
    "Hyperion Systems", "Aurora Tech", "Titan Edge", "Sky Bridge", "Everest Global",
    "Storm Works", "Nebula Dynamics", "Cyber Link", "Pixel Soft", "Cloud Nova",
    "Vertex Labs", "Radiant Tech", "Silver Line", "Prism Works", "Axion Systems",
    "Prime Core", "Falcon Tech", "Iron Works", "Pioneer Labs", "Echo Vision",
    "Summit Soft", "Data Sphere", "Bright Wave", "Quantum Edge", "Core Logic",
    "Epic Tech", "Strato Works", "True North Labs", "Infinity Global", "Next Phase",
    "Vector Works", "Rapid Edge", "Ignite Tech", "Crystal Core", "Storm Net",
    "Cyber Sphere", "Mega Tech", "Vertex Corp", "Blue Ocean", "Sky Labs",
    "Pulse Wave", "Astro Dynamics", "Solaris Global", "White Peak", "Cloud Bridge",
    "Iron Core", "Optima Tech", "Red Wave", "Aurora Edge", "Vortex Labs",
    "Meta Core", "Data Forge", "Star Link", "Neo Systems", "Eagle Vision",
    "Bright Path", "Zen Core", "Luna Soft", "Nova Edge", "Iron Shield",
    "Summit Global", "Pulse Works", "Cyber Edge", "Crystal Labs", "Prime Wave",
    "Blue Stone", "Core Vision", "Echo Tech", "Next Wave", "Cloud Sphere",
    "Rapid Systems", "Silver Peak", "Solar Net", "Quantum Core", "Golden Gate Tech", "Silver Horizon", "Iron Gate", "Bright Future", "Golden Path", "Crystal River",
    "Shadow Tech", "Blue Horizon", "Green Valley", "Red Mountain", "White Cloud",
    "Sky Bridge", "Ocean Wave", "Future Vision", "Core Dynamics", "Next Horizon",
    "Steel Tower", "Rapid Flow", "Solar Gate", "Lunar Vision", "True Path",
    "Cloud Harbor", "Bright Sky", "Deep Space", "Nova Point", "Zen Garden",
    "Iron Peak", "Quantum Gate", "Silver Lake", "Bright Star", "Neon Path",
    "Solar Vista", "Blue Peak", "Shadow Edge", "Crystal Valley", "River Stone",
    "Data Horizon", "Echo Path", "Summit Point", "Storm Valley", "Aurora Gate",
    "Pulse Harbor", "Starlight Vision", "Next Point", "Future Gate", "Iron River",
    "Silver Tower", "Red Gate", "Sky Vision", "Ocean Edge", "Bright Harbor",
    "Steel Path", "Quantum Valley", "Lunar Harbor", "True Peak", "Nova Gate",
    "Crystal Point", "Zenith Harbor", "Shadow Works", "Golden Horizon", "Blue Tower",
    "Green Path", "Echo Valley", "Data Harbor", "Storm Edge", "Bright Path",
    "Iron Stone", "Red Horizon", "Silver Vision", "Ocean Path", "Pulse Valley",
    "Future Works", "Solar Horizon", "Blue Harbor", "Crystal Edge", "Neon Vision",
    "Golden Harbor", "Quantum Star", "Shadow Peak", "White Horizon", "Steel Harbor",
    "Bright Edge", "Lunar Peak", "Silver Works", "Red Stone", "Echo Horizon",
    "Storm Tower", "Sky Harbor", "Aurora Point", "Pulse Gate", "Green Harbor",
    "Next Valley", "Crystal Tower", "Blue Stone", "Iron Vision", "Golden Valley",
    "Quantum Works", "Bright Tower", "Future Harbor", "Solar Edge", "Nova Valley",
    "Golden Lens", "Silver Shutter", "Bright Focus", "True Capture", "Crystal Frame",
    "Blue Horizon Photos", "Sunset Memories", "Pixel Studio", "Lightwave Photography", "Next Frame",
    "Dream Capture", "Starlight Studio", "Evergreen Photos", "Pure Vision", "Urban Lens",
    "Ocean View Photography", "Skyline Studio", "Memory Makers", "Radiant Capture", "Frozen Time",
    "Shutter Works", "Photo Haven", "Timeless Vision", "Bright Moments", "Clear Focus",
    "Echo Lens", "Flash Point", "Prism Studio", "Aurora Capture", "Nova Lens",
    "Luna Photography", "Silver Frame", "Color Splash", "Infinite Memories", "Sunrise Lens",
    "True North Photography", "Golden Hour Studio", "Living Memories", "Snapshot Works", "Vivid Moments",
    "Blue Sky Studio", "Ever After Photos", "Pure Light", "Zenith Lens", "Starlens Studio",
    "Future Memories", "Visionary Capture", "Shadow Frame", "Bright Eyes Photography", "Crystal Lens",
    "Photo Forge", "Memory Lane Studio", "Echo Frame", "Pulse Photography", "Pixel Forge",
    "Silver Shadows", "Radiant Lens", "Sunbeam Studio", "Golden Vision", "Timeless Studio",
    "True Colors Photography", "Blue Ocean Photos", "Bright Horizon", "Urban Capture", "Flash Works",
    "Solar Lens", "Crystal Vision", "Light Path Studio", "Sky Vision Photos", "Memory Vault",
    "Infinite Frames", "Color Bloom", "Aurora Memories", "Golden Gate Photos", "Clear View Studio",
    "Next Vision", "Starlight Capture", "Dream Lens", "Frozen Moments", "Vivid Lens",
    "Silver Light Studio", "Pure Capture", "Red Leaf Photography", "Zenith Photos", "Eternal Frame",
    "Blue Peak Studio", "Luminous Vision", "Timeless Lens", "Nova Memories", "Bright Light Photos",
    "Echo Works", "Prism Lens", "Photo Bloom", "True Light Studio", "Urban Vision",
    "Memory Craft", "Snapshot Studio", "Aurora Frame", "Shutter Bloom", "Golden Leaf Photography",
    "Bright Lens Studio", "Golden Hour Photography", "Crystal Light Images", "Silver Leaf Studio", "True Vision Photos",
    "Pure Frame Photography", "Skyline Lens", "Ocean Breeze Photos", "Sunrise Capture", "Twilight Moments",
    "Vivid Focus Studio", "Everlight Photography", "Color Frame", "Shutter Point", "Aurora Lens Studio",
    "Lunar Light Photos", "Pixel Horizon", "Memory Makers Studio", "Frozen Light", "Dreamshot Photography",
    "Blue Leaf Studio", "Starlight Capture", "Urban Moments", "Clear Sky Photography", "Timeless Frames",
    "Bright Horizon Photos", "Photo Harbor", "Sunset Lane Studio", "Eternal Memories", "Radiant Frames",
    "Echo Shot", "Silver Wave Photos", "Shadow Light Studio", "Next Chapter Photos", "Vision Works",
    "Ocean View Studio", "Prism Capture", "Aurora Frame Studio", "Living Light Photography", "Infinite Focus",
    "Blue Peak Photos", "Crystal Bloom Studio", "Memory Vault Photography", "True North Lens", "Bright Bloom",
    "Pixel Craft Studio", "Golden Dream Photos", "Ever After Frames", "Lightline Studio", "Nova Shot",
    "Zenith Capture", "Echo Vision Photography", "Frozen Shadows", "Sky Path Photos", "Pure Horizon Studio",
    "Timeless Glow", "Bright Path Photography", "Red Sky Studio", "Photo Bloom Studio", "Urban Focus",
    "Dream Vision Photos", "Snapshot Lane", "Clear Focus Studio", "Starlens Capture", "Blue Ridge Photos",
    "Radiant Light Studio", "Silver Frame Photos", "True Colors Studio", "Vivid Edge Photography", "Luna Horizon",
    "Golden Valley Photos", "Bright Leaf Studio", "Pulse Capture", "Photo Haven Studio", "Memory Lane Photos",
    "Next Vision Studio", "Shutter Bloom Studio", "Ocean Light Photography", "Zen Capture", "Crystal Edge Photos",
    "Aurora Sky Studio", "Frozen Vision", "Infinite Bloom Photography", "Echo Bloom Studio", "Sky Focus",
    "Color Wave Photos", "Shadow Lens Studio", "Bright Sky Studio", "Golden Leaf Images", "Blue Wave Capture",
    "Dream Frame Photography", "Timeless Path Studio", "Nova Vision Photos", "Starlight Frames", "True Horizon Photography",
    "Urban Light Studio", "Pixel Flow Photos", "Clear Path Studio", "Vivid Glow Photography", "Eternal Light Studio",
    "Quantum Labs", "Neural Net Systems", "Blue Circuit", "Cloud Matrix", "Cyber Vision",
    "Next Phase Tech", "Data Forge", "Iron Grid", "Bright Pixel", "Fusion Logic",
    "Silver Cloud", "Digital Path", "Hyper Core", "True Logic", "Core Nexus",
    "Prime Systems", "Echo Net", "Vertex Logic", "Pulse Dynamics", "Infinity Labs",
    "Rapid Logic", "Stellar Edge", "Bright Core", "Vector Dynamics", "Neon Flux",
    "Meta Wave", "Skyline Tech", "Future Logic", "Red Circuit", "Crystal Net",
    "Lunar Core", "Solar Logic", "Stream Works", "Pure Data", "Axion Tech",
    "Epic Logic", "Storm Net", "Blue Core", "Zenith Logic", "Pulse Core",
    "Iron Logic", "Next Wave Systems", "Core Sphere", "Fusion Net", "Nova Logic",
    "Radiant Net", "True Data", "Bright Logic", "Quantum Core", "Vertex Edge",
    "Cyber Point", "Red Nova", "Silver Net", "Cloud Vision", "Axion Works",
    "Iron Dynamics", "Neon Core", "Prime Net", "Sky Logic", "Blue Matrix",
    "Epic Dynamics", "Bright Wave", "Data Core", "Zenith Labs", "Pulse Logic",
    "Solar Net", "Next Core", "Iron Edge", "Crystal Logic", "Vector Net",
    "Hyper Works", "Future Edge", "True Systems", "Bright Vision", "Cloud Forge",
    "Cyber Edge", "Axion Labs", "Red Grid", "Blue Nexus", "Stellar Core",
    "Silver Dynamics", "Neon Labs", "Quantum Net", "Nova Edge", "Stream Tech",
    "Crystal Core", "Iron Sphere", "Rapid Labs", "Next Logic", "Meta Core",
    "Pulse Wave", "Zenith Edge", "Data Logic", "Bright Nexus", "Future Net",
    "Echo Core", "Storm Logic", "Prime Vision", "Sky Edge", "Blue Logic",
    "Core Link", "Fusion Edge", "Infinity Tech", "Solar Works", "Quantum Vision",
    "Wild Horizon", "Mountain Peak Adventures", "Golden Trail", "True North Travel", "Summit Quest",
    "Blue Sky Adventures", "Ocean Breeze Travel", "Rising Sun Tours", "Crystal Lake Expeditions", "Evergreen Journeys",
    "Starlight Adventures", "Bright Path Travel", "Next Horizon Tours", "Wanderlust Journeys", "Red Rock Expeditions",
    "Wild River Travel", "Pure Adventure", "Echo Valley Tours", "Sunset Horizon Travel", "Infinite Journeys",
    "Silver Compass", "Zenith Adventures", "Trail Blazers Travel", "Frozen Peak Expeditions", "Aurora Sky Tours",
    "Urban Nomad", "Timeless Journeys", "Skyline Adventures", "Blue Ocean Treks", "Summit Path Travel",
    "Bright Horizon Tours", "Nova Adventures", "True Spirit Travel", "Globe Trotters", "Epic Trail Adventures",
    "Golden Sands Travel", "Ocean Edge Journeys", "Star Path Tours", "Future Horizon Travel", "Everest Quest",
    "Crystal Summit Adventures", "Aurora Adventures", "Lunar Path Travel", "Echo Point Tours", "Skyline Treks",
    "Wild Leaf Adventures", "Iron Peak Travel", "Bright Horizon Adventures", "Dream Trail Tours", "Pure Horizon Travel",
    "Blue Ridge Treks", "River Stone Journeys", "Starlight Expeditions", "True Horizon Tours", "Next Chapter Travel",
    "Summit Valley Adventures", "Golden Gate Travel", "Frozen River Expeditions", "Vivid Horizon Tours", "Urban Escape Travel",
    "Aurora Vista Adventures", "Wander Path", "Silver Lake Journeys", "Crystal Valley Treks", "Infinite Horizons Travel",
    "Red Canyon Adventures", "Bright Star Travel", "Sky Trail Expeditions", "Nova Vista Tours", "Wild Peak Journeys",
    "Mountain Spirit Adventures", "Sunrise Horizon Travel", "Golden Leaf Treks", "Blue Mountain Tours", "Timeless Treks",
    "Lunar Sky Adventures", "Future Path Travel", "True Adventure Journeys", "Crystal River Tours", "Pulse Horizon Travel",
    "Bright Leaf Adventures", "Silver Peak Treks", "Urban Horizon Travel", "Aurora Spirit Tours", "Frozen Summit Expeditions",
    "Evergreen Adventures", "Wild Path Journeys", "Sky Quest Travel", "Dream Horizon Tours", "Golden Star Treks",
    "Ocean Spirit Adventures", "Echo Mountain Tours", "Starlens Travel", "Summit Glow Adventures", "Blue Lake Treks",
    "Red Horizon Travel", "Bright Sands Adventures", "Zenith Path Journeys", "Timeless Horizon Tours", "Nova Horizon Travel"
]